---
# Copyright (c) 2017 TIBCO Software Inc.
#
# file: Update_Cluster_Config.yml
# requires servicename
- hosts: ${ANSIBLE_HOST_GROUP}
  name: Update Cluster Config
  remote_user: ${ANSIBLE_REMOTE_USER}
  become: True
  become_user: "{{ SBUSER }}"
  gather_facts: true
  vars_files:
    - roles/tibcosbinstall/defaults/main.yml
    - roles/${CLUSTERNAME}/defaults/main.yml
    - roles/Cluster_Docker/defaults/main.yml
  environment: "{{ sb_env }}"
  ignore_errors: false

  tasks:
    - name: load existing node assignment
      include_vars: "{{ playbook_dir }}/roles/${CLUSTERNAME}/files/nodes_assignment.yml"
    - name: update hosts file
      become: True
      become_user: root
      include: ./roles/common/tasks/updatehostfile.yml
    - include: ./roles/{{ CLUSTER_NAME }}/tasks/load_cluster_config.yml servicename={{ CLUSTER_NAME }}
      run_once: true
      when: DOCKERDEPLOY == false
    - include: ./roles/{{ CLUSTER_NAME }}/tasks/activate_cluster_config.yml servicename={{ CLUSTER_NAME }}
      run_once: true
      when: DOCKERDEPLOY == false
    - include: ./roles/Cluster_Docker/tasks/load_cluster_config.yml docker_name={{ CLUSTER_NAME }}
      run_once: true      
      when: DOCKERDEPLOY
    - include: ./roles/Cluster_Docker/tasks/activate_cluster_config.yml docker_name={{ CLUSTER_NAME }}
      run_once: true
      when: DOCKERDEPLOY
