---
TIBCO_SB_DOCKER_IMAGE: ${SB_DOCKER_IMAGE}
TIBCO_SB_DOCKER_IMAGE_TAG: ${SB_DOCKER_IMAGE_TAG}
DOCKER_REGISTRY: ${DOCKER_REGISTRY}
DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
DOCKER_REGISTRY_AUTH: ${DOCKER_REGISTRY_AUTH}
DOCKER_REGISTRY_EMAIL: ${DOCKER_REGISTRY_EMAIL}
weave_headnode: "{{ groups['${ANSIBLE_HOST_GROUP}'][0] }}"
weave_headnode_ip: "{{ hostvars[weave_headnode]['ansible_default_ipv4']['address']}}"
