# Copyright (c) 2017 TIBCO Software Inc.
#
# file: display_node.yml

- name: display node
  command: "{{ EP_ADMIN_BIN }} servicename={{ servicename }} display node"
  register: cmd_result
  ignore_errors: True

- debug: var=cmd_result.stdout_lines

- debug: msg={{ cmd_result.stderr }}
