# Copyright (c) 2017 TIBCO Software Inc.
#
# global group vars for Cluster_Name already defined by Cluster role variable file main.yml
#
ssh_key: ${SSH_KEY_NAME}
ssh_user: ${ANSIBLE_REMOTE_USER}
node_count: ${NODE_COUNT} # number of sb nodes per instance/VM - at least 1
DOCKERDEPLOY: ${DOCKERDEPLOY}
CLUSTER_NAME: ${CLUSTERNAME}
TIBCO_INSTALL_DIR: ${TIBCO_INSTALL_DIR}
NODE_INSTALL_DIR: ${NODE_INSTALL_DIR}
SB_ADMIN_PORT: ${SB_ADMIN_PORT}
BUILDTYPE: ${BUILDTYPE}
SB_CEP_VERSION: ${SB_CEP_VERSION}
STREAMBASE_HOME: ${STREAMBASE_HOME}
TIBCO_EP_HOME: ${REMOTE_TIBCO_EP_HOME}
TIBCO_EP_BIN: ${TIBCO_EP_BIN}
EP_ADMIN_BIN: ${TIBCO_EP_BIN}/epadmin
SB_TARBALL: ${SB_TARBALL}
SB_TARBALL_URL: ${SB_TARBALL_URL}
SB_HA_DIR: "{{ TIBCO_INSTALL_DIR }}/highavailability"
SB_APP_FILE: ${SB_APP_FILE}
SB_APP_NAME: ${SB_APP_NAME}
SB_APP_DIR: ${SB_APP_DIR}
SB_APP_FILE_URL: ${SB_APP_FILE_URL}
SB_APP_CONFIG: test
DEPLOYDIR: ${DEPLOYDIR}
JAVA_HOME: /etc/alternatives/java_sdk_1.8.0
JAVA_OPTIONS: "'-DTIBCO_EP_HOME={{ TIBCO_EP_HOME }} -Xms512m -Xmx2048m'"
SBUSER: sbuser
NODE_CONFIG: ${NODE_CONFIG}
NODE_CONFIG_URL: ${NODE_CONFIG_URL}
# do not define for automatic discovery
SUBSTITUTIONS: ${SUBSTITUTIONS}
WEAVE_DOMAIN: ${CLUSTERNAME}.local.

# DO NOT EDIT ENV VARS BELOW - EDIT ABOVE
sb_env:
  TIBCO_INSTALL_DIR: "{{ TIBCO_INSTALL_DIR }}"
  NODE_INSTALL_DIR: "{{ NODE_INSTALL_DIR }}"
  SB_ADMIN_PORT: "{{ SB_ADMIN_PORT }}"
  BUILDTYPE: "{{ BUILDTYPE }}"
  SB_CEP_VERSION: "{{ SB_CEP_VERSION }}"
  STREAMBASE_HOME: "{{ STREAMBASE_HOME }}"
  TIBCO_EP_HOME: "{{ TIBCO_EP_HOME }}"
  TIBCO_EP_BIN: "{{ TIBCO_EP_BIN }}"
  SB_TARBALL: "{{ SB_TARBALL }}"
  SB_HA_DIR: "{{ SB_HA_DIR }}"
  SB_APP_FILE: "{{ SB_APP_FILE }}"
  SB_APP_NAME: "{{ SB_APP_NAME }}"
  SB_APP_DIR: "{{ SB_APP_DIR }}"
  SB_APP_CONFIG: "{{ SB_APP_CONFIG }}"
  DEPLOYDIR: "{{ DEPLOYDIR }}"
  JAVA_HOME: "{{ JAVA_HOME }}"
  JAVA_OPTIONS: "{{ JAVA_OPTIONS }}"
  CLUSTER_NAME: "{{ CLUSTER_NAME }}"
  SBUSER: "{{ SBUSER }}"
  NODE_CONFIG: "{{ NODE_CONFIG }}"
  SUBSTITUTIONS: "{{ SUBSTITUTIONS }}"
  A1_DATATRANSPORTPORT: 5557
  A2_DATATRANSPORTPORT: 5557
  A3_DATATRANSPORTPORT: 5557
  A1_NODENAME: ${nodename1}.${CLUSTERNAME}
  A2_NODENAME: ${nodename2}.${CLUSTERNAME}
  A3_NODENAME: ${nodename3}.${CLUSTERNAME}
  A1_IPADDR: ${nodename1}.${CLUSTERNAME}
  A2_IPADDR: ${nodename2}.${CLUSTERNAME}
  A3_IPADDR: ${nodename3}.${CLUSTERNAME}

node_substitutions:
  A1_DATATRANSPORTPORT: 5557
  A2_DATATRANSPORTPORT: 5557
  A3_DATATRANSPORTPORT: 5557
  A1_NODENAME: ${nodename1}.${CLUSTERNAME}
  A2_NODENAME: ${nodename2}.${CLUSTERNAME}
  A3_NODENAME: ${nodename3}.${CLUSTERNAME}
  A1_IPADDR: ${nodename1}.${CLUSTERNAME}
  A2_IPADDR: ${nodename2}.${CLUSTERNAME}
  A3_IPADDR: ${nodename3}.${CLUSTERNAME}
  
