# Copyright (c) 2017 TIBCO Software Inc.
#
# file: display_cluster.yml

- name: display cluster
  become: true
  command: "docker exec {{ docker_name }} {{ EP_ADMIN_BIN }} servicename={{ servicename }} display cluster"
  register: cmd_result
  ignore_errors: True

- debug: var=cmd_result.stdout_lines

- debug: msg=cmd_result.stderr
