# Copyright (c) 2017 TIBCO Software Inc.
#
# file: display_partition.yml

- name: display partition
  become: true
  command: "docker exec {{ docker_name }} {{ EP_ADMIN_BIN }}  servicename={{ servicename }} display partition"
  register: cmd_result
  ignore_errors: True

- debug: var=cmd_result.stdout_lines

- debug: msg=cmd_result.stderr
