# Copyright (c) 2017 TIBCO Software Inc.
#
# file: get_active_docker_nodes.yml
    - name:  get container names
      become: True
      become_user: root
      shell: docker ps --format '{{ '{{' }}.Names{{ '}}' }}'
      register: active_nodes_result
