# Copyright (c) 2017 TIBCO Software Inc.
#
# file: load_cluster_config.yml
   - name: load node config
     become: true
     command: "docker exec {{docker_name}} {{ EP_ADMIN_BIN }} servicename={{ docker_name }} load configuration source={{ SB_APP_DIR }}/{{ NODE_CONFIG }} substitutions={{ SUBSTITUTIONS }}"
     register: load_cmd_result

   - debug: var=load_cmd_result
