# Copyright (c) 2018 TIBCO Software Inc.
#
    - name: create docker compose file from template
      template: src=docker-compose.j2 dest="{{ playbook_dir }}/roles/Cluster_Docker/files/docker-compose.yml"
      delegate_to: 127.0.0.1
      run_once: true

    - name: copy docker-compose.yml to remote swarm manager
      synchronize: src="{{ playbook_dir }}/roles/Cluster_Docker/files/docker-compose.yml" dest={{SB_APP_DIR}}/docker-compose.yml

    - name: remove existing stack services
      command: docker stack rm {{SB_APP_NAME}}
      delegate_to: "{{ swarm_manager }}"
      
    - name: deploy SB app stack to swarm
      shell: "docker stack deploy --resolve-image always -c {{SB_APP_DIR}}/docker-compose.yml {{SB_APP_NAME}}"
      delegate_to: "{{ swarm_manager }}"
      register: stackoutput

    - debug:
        var: stackoutput
      delegate_to: "{{ swarm_manager }}"
