# Copyright (c) 2017 TIBCO Software Inc.
#
    - name: create app directory
      file: path={{ SB_APP_DIR }} state=directory recurse=yes owner={{ SBUSER }} group=sbusers
    - name: download application
      become: True
      become_user: root
      copy: src={{ SB_APP_FILE_URL }}/{{ SB_APP_FILE }} dest={{ SB_APP_DIR }} owner={{ SBUSER }} group=sbusers
    - name: copy node config
      copy: src={{ NODE_CONFIG_URL }}/{{ NODE_CONFIG }} dest={{ SB_APP_DIR }} owner={{ SBUSER }} group=sbusers    
