---
# Copyright (c) 2017 TIBCO Software Inc.
#
# file: cloud_site.yml
# ansible-playbook cloud_site.yml --extra-vars "CLUSTER_NAME=topologies,provider=ec2"
- set_fact: 
    cloud: ec2
  when: provider is undefined
- include: playbooks/ec2_provision.yml
  when: provider == "ec2"
